trigger:
    branches:
      include:        
        - develop
        - release/*
  
pool:
  vmImage: "ubuntu-latest"

pr: none

variables: 
  BuildConfiguration: 'release'
  
steps:
  - task: gitversion/setup@0
    inputs:
      versionSpec: '5.1'
      includePrerelease: true
    displayName : "Configurando gitversion"

  - task: gitversion/execute@0
    inputs:
      useConfigFile: true
      configFilePath: "deploy/gitConfig.yml" 
    displayName: "generando la nueva versión"
  
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'
      vstsFeed: '$(default-feed)'
      includeNuGetOrg: false 
      versioningScheme: byBuildNumber


  
  - task: DotNetCoreCLI@2
    displayName: 'dotnet pack' 
    inputs: 
      command: pack
      packagesToPack: '**/trifenix-main.csproj'       
      arguments: '--configuration $(BuildConfiguration) /p:Version=$(NuGetVersion)' 
      versioningScheme: byEnvVar 
      versionEnvVar: NuGetVersion

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: drop
      publishLocation: 'container'
    displayName: "publish nuget"