trigger:
    branches:
      include:        
        - develop
        - release/*
  
pool:
  vmImage: "ubuntu-latest"

steps:

 
    
  - task: gitversion/setup@0
    inputs:
      versionSpec: '5.1'
      includePrerelease: true
    displayName : "Configurando gitversion"

  - task: gitversion/execute@0
    inputs:
      useConfigFile: false
    displayName: "generando la nueva versión"
  
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'
      vstsFeed: '$(default-feed)'

  - task: CmdLine@2
    inputs:
      script: |
        echo ${NuGetVersion}
        
        echo Hello world
    
    
  - task: DotNetCoreCLI@2
    displayName: "dotnet pack"
    inputs:
      command: 'pack'
      packagesToPack: '**/trifenix-main.csproj'      
      packDirectory: '$(Build.ArtifactStagingDirectory)'
      versionEnvVar: '${NuGetVersion}'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: drop
      publishLocation: 'container'
    displayName: "publish nuget"