mode: ContinuousDelivery
branches:
  main:
    regex: ^master$|^main$
    tag: ''
  feature:
    tag: alpha
  release:
    tag: rc
  develop:
    tag: beta
  


ignore:
  sha: []
merge-message-formats: {}